nspcc-dev/neofs-contract

neofs_contract.go

Inner ring nodes check their presence in inner ring list during startup. `IsInnerRing` method allows to check presence efficiently by calling this method. This method returns `true` if provided public key is present in inner ring list. Otherwise returns `false`.

Add "IsInnerRing" method

---

README.md
neofs_contract.go
neofs_contract_test.go

Inner ring nodes do not collect signatures for the cheque now. Instead they invoke "InnerRingUpdate" method and smart-contract checks if method was called from inner ring node. Then it accepts cheque if there were 2/3n+1 invokes.

Collect "InnerRingUpdate" calls from inner ring nodes 

---

neofs_contract.go

New methods allow to bind and unbind public keys with the owner, therefore the user can store and access data with the key, that does not related to the wallet.

Add "Bind" and "Unbind" methods

---

netmap/netmap_contract.go

There are cases when NeoFS applications need to fetch netmap snapshot of exact epoch. This method provides convenient atomic
way to do that. 
Related to https://github.com/nspcc-dev/neofs-node/issues/234

Add snapshot getter by epoch number

---

container/config.yml
container/container_contract.go

Basic income settlements depends on container estimation that should be collected in P2P communication between storage nodes
and then stored in container contract. To synchronize these actions there are two separate notification that inner ring should produce in consensus.

Produce notification to control container estimations

---

balance/balance_contract.go
container/container_contract.go
neofs/neofs_contract.go
neofsid/neofsid_contract.go
netmap/netmap_contract.go

Remove old ballots first so there won't be any
interference with votes of the same tx in the
future after `blockDiff` blocks.
Signed-off-by: Alex Vanin <alexey@nspcc.ru>

Fix processing order in voting

---

alphabet/config.yml
audit/config.yml
container/config.yml
neofs/config.yml
neofsid/config.yml
netmap/config.yml
reputation/config.yml

Closes #39 
It is required field in contract config for deployment.

Add contract names

---

balance/balance_contract.go
container/container_contract.go
neofsid/neofsid_contract.go
netmap/netmap_contract.go

Closes #53 
Additionally: 
- remove unused code from neofsid contract after notary update,
- use `interop.Hash160` type for contract addresses fetched from storage in container contract.

Run cleanup routines on new epoch

---

common/ir.go
neofs/neofs_contract.go

`x*2/3` is not equal to `x/3*2` with integers. The only correct way to calculate threshold is the first one.

Fix threshold number calculation

---

audit/audit_contract.go
reputation/config.yml
reputation/reputation_contract.go

This PR also removes usage of integers as a storage search prefix, because it may behave inconsistently.

Update reputation contract

---

balance/balance_contract.go
common/transfer.go
container/container_contract.go

Unified format uses transfer type as the first byte and extra details next. List of transfer types used in contracts defined in `transfer.go`. It includes:
- mint,
- burn,
- lock,
- unlock,
- container fee.

Unify transfer deatails format

---

alphabet/alphabet_contract.go
audit/audit_contract.go
balance/balance_contract.go
container/container_contract.go
neofs/neofs_contract.go
neofsid/neofsid_contract.go
netmap/netmap_contract.go

There is a number of contracts which return only `true` value.
Also handling `FAULT` on the client is easier then also checking return
value.
Close #79 .

[#79] Panic instead of returning bool value

---

netmap/config.yml
netmap/netmap_contract.go

With `NetmapCandidate` storage nodes can monitor if they are expected to be in the netmap at next epoch or not. This is also important for monitoring when some nodes does not bootstrap immediately.
Closes #66

Add netmap candidate list getter

---

container/config.yml
neofs/config.yml
netmap/config.yml

neo-go v0.95.2+ has strict notification type checker enabled by default.
Closes #93

Fix parameter types in notification manifest

---

alphabet/config.yml
audit/config.yml
balance/config.yml
container/config.yml
neofs/config.yml
neofsid/config.yml
netmap/config.yml
processing/config.yml
proxy/config.yml
reputation/config.yml

Before neo-go v0.95.2 all permissions were '*', but it has been changed.

Specify permissions in contract manifests

---

alphabet/alphabet_contract.go
audit/audit_contract.go
balance/balance_contract.go
neofs/neofs_contract.go
neofsid/neofsid_contract.go
netmap/netmap_contract.go
processing/processing_contract.go
proxy/proxy_contract.go

Make `AddPeer` stable for simultaneous invocations in one block

---

Makefile

Without -o flag neo-go compiles contracts into `out.nef` file in the repository root.

Fix Makefile after NNS contract

---

Makefile

Close #95. 
This is something I used for myself, we can alter it in future if needed.
It contains only *.nef and *.json files.

Makefile: allow target for creating release archive

---

nns/nns.yml
nns/nns_contract.go

The old contract was compiled in a such way that `Update` used
all flags except `AllowCall`. Because of this it is impossible to
calculate the key of any record as it requires `Crypto` native contract.
Thus we iterate over all records and transform them into the
serialized representation (`std.Serialize` doesn't work either).
The `Name` field in the resulting structure is empty but this is not a
big deal, `getRecord` continues to work.

Update NNS contract

---

alphabet/alphabet_contract.go
audit/audit_contract.go
balance/balance_contract.go
container/container_contract.go
neofs/neofs_contract.go
neofsid/neofsid_contract.go
netmap/netmap_contract.go
processing/processing_contract.go
proxy/proxy_contract.go
reputation/reputation_contract.go

Neo Legacy used migration mechanism to update contracts. N3 provides update method in native management contract. Therefore, it makes sense to rename `Migrate` to `Update`.
Closes #128

Rename migrate methods to update

---

alphabet/alphabet_contract.go
audit/audit_contract.go
balance/balance_contract.go
common/ir.go
common/update.go
container/container_contract.go
neofs/neofs_contract.go
neofsid/neofsid_contract.go
netmap/netmap_contract.go
processing/processing_contract.go
proxy/proxy_contract.go
reputation/reputation_contract.go

Do not save contract owner at the contract deploy stage. Use side chain committee witness to migrate contracts.
Close #107

Remove contract owners

---

nns/nns_contract.go

No longer needed, see 978a43cec.

nns: remove migration in `_deploy`

---

container/config.yml
container/container_contract.go
nns/config.yml
tests/balance_test.go
tests/basic.go
tests/compile.go
tests/container_test.go
tests/netmap_test.go

Close #134 .
Adressing some issues:
1. Container contract is the owner of all domains.
2. Renewing can be done via direct invocation of NNS contract. Currently there is no owner check, so anyone (alphabet) can pay GAS to renew domain.
3. Cybersquatting is possible, because anyone can register a domain. One way to prevent this is to allow registering "restricted" roots which need a committee signature to register domains in.

Register nice names for new containers

---

reputation/config.yml

Also make it possible to compile with the latest neo-go version.

reputation: fix safe method names

---

netmap/netmap_contract.go
tests/netmap_test.go

Only alphabet calls are allowed.
Depends on #147 (tests) .

Fix notary-enabled logic in netmap contract

---

netmap/netmap_contract.go
tests/netmap_test.go

netmap: allow only alphabet calls in `updateState`

---

nns/nns_contract.go
tests/nns_test.go

Close #165 .
So we already iterate over records to checking for duplicates doesn't seem to introduce a big overhead.

nns: disallow record duplicates

---

alphabet/alphabet_contract.go
audit/audit_contract.go
balance/balance_contract.go
common/version.go
container/container_contract.go
neofs/neofs_contract.go
neofsid/neofsid_contract.go
netmap/netmap_contract.go
nns/nns_contract.go
processing/processing_contract.go
proxy/proxy_contract.go
reputation/reputation_contract.go

We will need it also for #163 . I don't like the current interface (we need to append to args in `Update` if contract has any deploy-parameters), but at least it is something.
Related #158 .

nns: fail if previous version is incorrect

---

nns/nns_contract.go
tests/nns_test.go

Close #180.
Both amazon bucket naming rules and DNS label names prohibit hyphen as
first or last character, but allow it in the middle.

nns: allow hyphen in names

---

nns/nns_contract.go
tests/nns_test.go

Close #172 .
So there are two problems which needs to be discussed:
1. I register a domain `a.com` and register an A record `y.z.a.com` for it. What should happen if I register `z.a.com` domain? Current behaviour: fail registration with the error message showing conflicting record.
2. I register a domain `y.z.com` and a record `x.y.z.com`. What happens with record `x.y.z.com`?
Current behaviour: it will fail to resolve.

nns: allow to register arbitrary-level domains

---

netmap/netmap_contract.go
tests/netmap_test.go

Close #154.
For notary-disabled environment it makes sense to split node
registration and actual candidate update into separate methods.
This way we have less complicate logic in `AddPeer` and overall
registration flow is more understandable.

[#154] netmap: implement `Register` method

---

common/ir.go

Current height makes it impossible to change
roles and make some operations in one block.
Also, it may lead to accepting some operations
that are approved by already not valid alphabet.
Signed-off-by: Pavel Karpy <carpawell@nspcc.ru>

Fix/Check `NeoFS` role for the next block

---

reputation/reputation_contract.go

1. Ignore keys unrelated to reputation values
2. Remove legacy `contractOwner` key
3. Remove reinitialized data
Signed-off-by: Alex Vanin <alexey@nspcc.ru>

reputation: Fix migration routine

---

CHANGELOG.md
common/version.go
reputation/reputation_contract.go
subnet/subnet_contract.go

While updating v0.13.1 to v0.14.0 some errors emerged:
1. Subnet contract does not append version.
2. Reputation contract should no longer have transition code.

Fix reputation and subnet contract update

---

nns/nns_contract.go

If I understand correctly, `maxDomainNameFragmentLength` means maximum length of label of domain name. 
By [wiki](https://en.wikipedia.org/wiki/Domain_Name_System#Domain_name_syntax,_internationalization) and [spec](https://datatracker.ietf.org/doc/html/rfc1034#section-3.1):
```
A label may contain zero to 63 characters. The null label, of length zero, is reserved for the root zone. The full domain name may not exceed the length of 253 characters in its textual representation
```
But now we compare with 62 and don't allow labels with 63 octets length.

Fix maxDomainNameFragmentLength

---

CHANGELOG.md
nns/nns_contract.go
tests/container_test.go
tests/nns_test.go

Provide NNS domain expiration in `register`

---

container/config.yml

Remove "addRoot" method from the list of allowed methods, because
NNS doesn't have it since
https://github.com/nspcc-dev/neofs-contract/pull/139/commits/4b86891d57ef12c3f37a9ef27902c73d96812934.

Adjust container-contract permissions

---

CHANGELOG.md
netmap/netmap_contract.go
tests/netmap_test.go

* relates to #269
I've changed format of the Netmap contract storage - should I do some compatibility actions? @fyrchik

netmap: Return same type from reading methods

---

.gitignore
Makefile

Close #285.
`go install` doesn't have `-o` flag but it respects `GOBIN` environment variable.
Signed-off-by: Evgenii Stratonikov <evgeniy@morphbits.ru>

[#285] Makefile: Install neo-go in the current directory

---

container/config.yml
container/container_contract.go
tests/container_test.go
tests/util.go

Add method that allows to iterate over estimation records.
Update tests to assert that list of estimations built with existing methods is identical to estimations from iterator.

[#293] container: Add IterateContainerSizes method

---

container/config.yml
container/container_contract.go
tests/container_test.go

Signed-off-by: Evgenii Stratonikov <evgeniy@morphbits.ru>

container: allow to iterate over container list

---

netmap/doc.go

* relates to #275
I hope this will help us to carefully migrate contract data on update in future. Format suggestions are welcome. I thought about `.md`.

netmap: Document memory model

---

container/config.yml
container/container_contract.go
tests/container_test.go

I want to include this into 0.17.0 to have something for the nspcc-dev/neofs-node#2173 to use.

Correct getcontainersize api

---

container/container_contract.go
tests/container_test.go

container: Check eACL input in `setEACL` method's implementation

---

CHANGELOG.md
common/vote.go

On a real healthy network we _always_ have something there. Consider seven IRs doing something, we only need five signatures, so they're added and then dropped when we have enough of them, but excessive transactions from the other IRs still come and they will be added again into the same voting structure.
But according to the definition of blockDiff we can ignore stale votes safely (they're not counted for votes anyway).

common: ignore stale votes in TryPurgeVotes

---

CHANGELOG.md
container/config.yml
netmap/config.yml
reputation/config.yml
reputation/reputation_contract.go
subnet/config.yml

Drop old events

---

alphabet/doc.go
audit/doc.go
balance/doc.go
container/doc.go
neofs/doc.go
neofsid/doc.go
netmap/doc.go
processing/doc.go
proxy/doc.go
reputation/doc.go
subnet/doc.go

Document contracts' storage models

---

.github/workflows/config/.golangci.yml
.github/workflows/go.yml
.gitignore
CHANGELOG.md
Makefile
README.md
neofs/config.yml
rpc/alphabet/rpcbinding.go
rpc/audit/rpcbinding.go
rpc/balance/rpcbinding.go
rpc/container/rpcbinding.go
rpc/neofs/rpcbinding.go
rpc/neofsid/rpcbinding.go
rpc/netmap/rpcbinding.go
rpc/nns/rpcbinding.go
rpc/processing/rpcbinding.go
rpc/proxy/rpcbinding.go
rpc/reputation/rpcbinding.go
rpc/subnet/rpcbinding.go

~~Waiting for 0.102.0 release of neo-go to convert from draft.~~
UPD: we'll use fresh NeoGo master to build SCs and RPC bindings.

Makefile: generate RPC bindings

---

Makefile
audit/audit_contract.go
container/container_contract.go
neofs/neofs_contract.go
rpc/audit/rpcbinding.go
rpc/container/rpcbinding.go
rpc/neofs/rpcbinding.go
rpc/netmap/rpcbinding.go

And upgrade NeoGo to fetch the generator bugfix.
Close #349.

rpc: export unexported fields of public structures

---

nns/nns_contract.go
tests/nns_test.go

If a TLD has expired:
* it can't be renewed because of "name has expired"
* it can't be registered again because of "TLD already exists"
The first one is OK, but the second one is fixed here.

nns: fix expired TLD registration

---

CHANGELOG.md
README.md

btw we can go further and use `goimports` tool since imports are unsorted, but i decided to not do that for now
with these changes `make fmt` (`go fmt ./...`) becomes no-op

`go fmt` generated code

---

reputation/doc.go
reputation/reputation_contract.go

Maybe it's not perfect, but at least it's better than the old one.

reputation: drop copy/paste garbage from the doc, fix #331

---

alphabet/alphabet_contract.go
balance/balance_contract.go
balance/config.yml
common/netmap.go
common/nns.go
container/config.yml
container/container_contract.go
netmap/config.yml
netmap/migration_test.go
netmap/netmap_contract.go
rpc/netmap/rpcbinding.go
tests/alphabet_test.go
tests/container_test.go
tests/migration/storage.go
tests/neofsid_test.go
tests/netmap_test.go
tests/nns_test.go
tests/proxy_test.go

Do not hardcode container and balance contract as a `NewEpoch` events receivers in the netmap contract. Use the netmap's registration method on a deploy stage instead.

feat/Make `NewEpoch` callback mechanism more generic

---

alphabet/alphabet_contract.go
alphabet/migration_test.go
audit/audit_contract.go
audit/migration_test.go
balance/balance_contract.go
balance/migration_test.go
common/netmap.go
common/nns.go
container/container_contract.go
container/doc.go
container/migration_test.go
neofsid/migration_test.go
neofsid/neofsid_contract.go
netmap/migration_test.go
netmap/netmap_contract.go
reputation/migration_test.go
reputation/reputation_contract.go
tests/alphabet_test.go
tests/balance_test.go
tests/container_test.go
tests/neofsid_test.go
tests/netmap_test.go
tests/nns_test.go
tests/proxy_test.go

#370 replacement, sorry (`-f` and `-d` are pretty close on the keyboard).

Drop deploy configs

---

CHANGELOG.md
common/ir.go
contracts/alphabet/config.yml
contracts/alphabet/contract.go
contracts/proxy/contract.go
rpc/alphabet/rpcbinding.go
tests/alphabet_test.go
tests/helpers.go
tests/proxy_test.go

There is no way to move NEO from the Alphabet contracts right now. This can be needed for some migrations or fixes.
Proxy contract already had this method, so functionality is shared b/w them.
Closes #386.

alphabet: Add `verify` method

---

LICENSE.md
deploy/alphabet.go
deploy/contracts.go
deploy/deploy.go
deploy/deploy_test.go
deploy/funds.go
deploy/funds_test.go
deploy/netmap.go
deploy/nns.go
deploy/notary.go
deploy/util.go

Move contract deployment

---

rpc/nns/hashes.go

Inspired by https://github.com/nspcc-dev/neofs-node/pull/2841.

NNS wrapper extensions

---

CHANGELOG.md
LICENSE.md
README.md
scripts/compare-fscontent/compare-fscontent.go

May be used to check data consistency between different chain versions.

scripts: add script for containers and netmap entries comparison

---

deploy/alphabet.go
deploy/deploy.go
deploy/notary.go

It is possible to start blockchain with required roles already set. In this case, there is no need to wait for NNS to be deployed for GAS transfers, since notary service (requires Notary roles to be set correctly) is ready. It allows all multi-signed operations to be applied at an earlier stage. Closes #409.

deploy: transfer GAS in the first place if notaries are set

---

deploy/notary.go

The whole `makeUnsignedDesignateCommitteeNotaryTx` is designed to be called many times if something goes wrong. But currently neo-go's actor shares signers with TXs it produces, so the actor is broken immediately after this func is called. Can be seen only if transaction-to-sign is expired, in practice happened when deployment nodes were started with a huge delay.

deploy: copy transaction expected to be changed

---

.github/workflows/go.yml
Makefile
README.md
tests/container_test.go

WIP, waiting for the next NeoGo release to upgrade, but I have this code locally, so anyway it will be helpful.
Close #429.

*: enable coverage

---

CHANGELOG.md
deploy/deploy.go
deploy/util.go

Header subscription is available since NeoGo 0.105.0 and we don't need full block data.

deploy: subscribe to headers, not blocks

---

contracts/container/contract.go

38ac6f61f346d6c9e4a9c9d70e1d5e1b01b1845d breaks all Go conventions for function comments.

container: move deprecation notices into proper places

---

CHANGELOG.md
deploy/util.go

Block count is not block height, so this was always initialized improperly which can lead to missing one block event (and reacting only to subsequent one) when deploying a contract with a freshly initialized monitor.

deploy: fix off by one error in block monitor
