nspcc-dev/neofs-contract

neofs_contract.go
neofs_contract_test.go

With neo:morph environment, there will be no direct communication between inner ring nodes and storage nodes. neo:morph smart-contracts will identify inner ring nodes by their signatures.

Do not store multiaddress of inner ring nodes

---

neofs_contract.go
neofs_contract_test.go

Withdraw operation works a bit different with `neo:morph`. User calls `Deposit` and `Withdraw` methods that produce notifications for the inner ring nodes.
`Deposit` method does not produce feedback, but `Withdraw` does. Inner ring nodes check if user eligible to withdraw assets. If so, nodes invoke `Cheque` method. This method collects invocations from inner ring nods. When there are `2/3n+1` invocations, smart-contract transfers assets back to the user and produces notifications.

Update withdraw mechanism

---

go.mod
go.sum
neofs_config.yml
neofs_contract.go

Neo-go v0.90.0-pre implements neo3 features.

Update neo-go to v0.90.0-pre and fix smart-contract

---

neofs_contract.go

Add neofs install configuration

---

neofs_contract.go

Verify initial inner ring size and keys

---

alphabet/alphabet.tpl
alphabet/az/az_contract.go
alphabet/buky/buky_contract.go
alphabet/dobro/dobro_contract.go
alphabet/glagoli/glagoli_contract.go
alphabet/jest/jest_contract.go
alphabet/vedi/vedi_contract.go
alphabet/zhivete/zhivete_contract.go

Alphabet contracts are holders of NEO token in sidechain. Inner ring nodes control sidechain validators list by voting with corresponding alphabet contracts. Inner ring list itself controlled from mainnet.

Add vote method in alphabet contracts

---

netmap/netmap_contract.go

Do not save ballots for invalid epoch in netmap contract

---

container/container_contract.go

Return all available containers in `List(nil)`

---

audit/audit_contract.go

Closes #27 
Blocked by #23 
In updated audit scheme, contract stores marshalled audit result structure and provides interface to list them by epoch, container or exact audit executor.

Update audit contract

---

container/container_contract.go

Closes #22 
Container contract checks signature of eACL iterating through keys from neofsid contract.
Clients often ask eACL from storage nodes, but it's kinda hard for them to check signature since they have no direct access to neofsid contract. So the container contract can make one more iteration through keys from neofsid contract and return suitable one.

Return public key along with eACL signature

---

container/container_contract.go

Closes #38 
Container size estimations used for basic income settlement.
Also may be used for network statistic.

Save container size estimations

---

alphabet/alphabet_contract.go
audit/audit_contract.go
balance/balance_contract.go
common/update.go
container/container_contract.go
go.mod
go.sum
neofs/neofs_contract.go
neofsid/neofsid_contract.go
netmap/netmap_contract.go
reputation/reputation_contract.go

Contract migration

---

Makefile
alphabet/alphabet_contract.go
balance/balance_contract.go
common/ir.go
container/container_contract.go
go.mod
go.sum
neofsid/neofsid_contract.go
netmap/netmap_contract.go
proxy/config.yml
proxy/proxy_contract.go

Support notary contract

---

netmap/netmap_contract.go

Use interop to create multi signature account

---

alphabet/alphabet_contract.go
audit/audit_contract.go
balance/balance_contract.go
common/ir.go
container/container_contract.go
neofs/config.yml
neofs/neofs_contract.go
neofsid/neofsid_contract.go
netmap/config.yml
netmap/netmap_contract.go
proxy/proxy_contract.go

Update governance model

---

neofs/neofs_contract.go

Cheques increase execution costs but provide which is quite important for main chain execution.
Closes #69

Do not store cheques

---

alphabet/alphabet_contract.go
audit/audit_contract.go
balance/balance_contract.go
container/container_contract.go
neofs/neofs_contract.go
neofsid/neofsid_contract.go
netmap/netmap_contract.go
processing/processing_contract.go
proxy/proxy_contract.go
reputation/reputation_contract.go

[#72] Replace `Init()` methods with `_deploy`

---

neofs/neofs_contract.go

Close #71 .
Testing is in process.

neofs: remove `deposit` method

---

alphabet/alphabet_contract.go
balance/balance_contract.go
common/vote.go
container/config.yml
neofsid/neofsid_contract.go

This PR fixes couple of typos and removes unused code.

Format code a bit

---

CHANGELOG.md

Restore the chronology of changes in changelog

---

container/config.yml
container/container_contract.go

Closes #76 
Also adds support of session token with container context.

Approve SetEACL invocations by alphabet

---

alphabet/alphabet_contract.go
audit/audit_contract.go
balance/balance_contract.go
container/container_contract.go
neofs/neofs_contract.go
neofsid/neofsid_contract.go
netmap/netmap_contract.go
processing/processing_contract.go
proxy/proxy_contract.go
reputation/reputation_contract.go

Migrate container and eACL structures from v0.8.0

---

container/container_contract.go

Closes #91 
Closes #90
Balance check at `container.Put` command will drop some invalid transactions from the side chain network before inner ring approval.

Add balance check before new container notification

---

container/container_contract.go

Fix unstable container methods

---

CHANGELOG.md
README.md
reputation/reputation_contract.go

Release v0.9.2

---

alphabet/alphabet_contract.go

Fix/Do not emit GAS to `proxy` if notary disabled

---

netmap/netmap_contract.go

Related to https://github.com/nspcc-dev/neofs-node/pull/708

netmap: Store block number of current epoch

---

Makefile
nns/config.yml
nns/namestate.go
nns/nns.yml
nns/nns_contract.go
nns/recordtype.go

Add NNS contract

---

container/container_contract.go
netmap/netmap_contract.go

Remove to v0.9.2 migration code

---

neofs/neofs_contract.go
netmap/netmap_contract.go

netmap: provide default configuration in `_deploy`

---

container/container_contract.go

Do not fail with PICKITEM error on non-existent container operations

---

alphabet/alphabet_contract.go
audit/audit_contract.go
balance/balance_contract.go
container/container_contract.go
neofs/neofs_contract.go
neofsid/neofsid_contract.go
netmap/netmap_contract.go
processing/processing_contract.go
proxy/proxy_contract.go
reputation/reputation_contract.go

There are no practical cases not to panic at contract update routine.
/cc @AnnaShaleva @fyrchik

Panic at contract update failures

---

nns/nns_contract.go
nns/recordtype.go

Added:
* Support multiple records of the same type
* SOA record
closes #125 
Signed-off-by: Denis Kirillov <denis@nspcc.ru>

[#125] Zone transfer

---

netmap/netmap_contract.go
tests/netmap_test.go

Revert recent netmap changes

---

go.mod
go.sum
tests/netmap_test.go

netmap: fix tests

---

reputation/reputation_contract.go
tests/reputation_test.go

reputation: fix concurrent `Put` invocations

---

neofsid/neofsid_contract.go
tests/neofsid_test.go

neofsid: allow multiple `addKey` per block

---

Makefile
subnet/config.yml
subnet/subnet_contract.go
tests/subnet_test.go

Support put/get/delete methods.
Related #122 .
Depends on #168 .

Initial subnet contract implementation

---

tests/nns_test.go

nns: add test for TLD record registration

---

container/container_contract.go

container: setup nns keys during update

---

audit/audit_contract.go
common/transfer.go
container/container_contract.go
neofsid/neofsid_contract.go
netmap/netmap_contract.go
subnet/subnet_contract.go

Closes #178. In `subnet` contract `// V2 format check` changed to `// V2 format`.

Doc/Add comments to V2 related checks

---

neofs/neofs_contract.go
tests/neofs_test.go

neofs: allow to register multiple candidates per block

---

neofsid/neofsid_contract.go
reputation/reputation_contract.go

Close #101, see https://github.com/nspcc-dev/neofs-contract/issues/101#issuecomment-982412353

[#101] *: update storage after voting

---

container/container_contract.go
nns/nns_contract.go
tests/container_test.go

Keep container contract as owner of `.container` zone

---

CHANGELOG.md
common/version.go

Release v0.13.2

---

nns/nns_contract.go

Feat/Provide additional `data` in `Update`

---

proxy/proxy_contract.go

[#205] proxy: do not store netmap hash

---

alphabet/alphabet_contract.go
audit/audit_contract.go
balance/balance_contract.go
common/update.go
container/container_contract.go
neofsid/neofsid_contract.go
netmap/netmap_contract.go
proxy/proxy_contract.go

Close #202 .
It is no longer used and should've be removed on update.

*: remove owner from contract storage

---

neofs/neofs_contract.go
processing/processing_contract.go

[#209] *: use current block index in `GetDesignatedByRole`

---

go.mod
go.sum

go.mod: update neo-go

---

nns/nns_contract.go

I have queried both testnet and mainnet.
There are no duplicates in testnet, however in mainnet we have SOA records stored with id 0 and "000" (3 bytes).
Tested this with testinvoke.

nns: remove duplicate records in `_deploy`

---

alphabet/alphabet_contract.go
audit/audit_contract.go
balance/balance_contract.go
neofs/neofs_contract.go
neofsid/neofsid_contract.go
netmap/netmap_contract.go
proxy/proxy_contract.go
reputation/reputation_contract.go
subnet/subnet_contract.go

*: remove update migration code

---

netmap/netmap_contract.go
tests/netmap_test.go

Close #224 , depends on #225 .

Increase snapshot history size

---

netmap/netmap_contract.go
tests/netmap_test.go

Require `UpdateState` to be called by both storage node and the alphabet
in notary-enabled environment, fail if only one of the signatures is present.
`UpdateStateIR` can be use for force updates by the alphabet.

netmap: improve `UpdateState` in notary-enabled environment

---

alphabet/alphabet_contract.go
audit/audit_contract.go
balance/balance_contract.go
common/ir.go
common/version.go
common/vote.go
container/container_contract.go
neofs/neofs_contract.go
neofsid/neofsid_contract.go
netmap/netmap_contract.go
reputation/reputation_contract.go

Close #222.
This leads to simpler code and lower GAS cost for transactions.
Also do some other optimizations.

Remove IRNode from sidechain contracts

---

netmap/netmap_contract.go

[#222] netmap: Store public keys in `_deploy`

---

neofs/neofs_contract.go
netmap/netmap_contract.go
tests/netmap_test.go

Configure netmap snapshot history size

---

README.md
alphabet/alphabet_contract.go
alphabet/doc.go
audit/audit_contract.go
audit/doc.go
balance/balance_contract.go
balance/doc.go
common/ir.go
common/transfer.go
common/vote.go
common/witness.go
container/container_contract.go
container/doc.go
neofs/doc.go
neofs/neofs_contract.go
neofsid/doc.go
neofsid/neofsid_contract.go
netmap/doc.go
netmap/netmap_contract.go
nns/nns_contract.go
nns/recordtype.go
processing/doc.go
processing/processing_contract.go
proxy/doc.go
proxy/proxy_contract.go
reputation/doc.go
reputation/reputation_contract.go
subnet/doc.go
subnet/subnet_contract.go
tests/alphabet_test.go

Checked for some inaccuracies regarding English.
Signed-off-by: Elizaveta Chichindaeva <elizaveta@nspcc.ru>

English Check

---

container/config.yml
container/container_contract.go
tests/container_test.go

[#242] container: allow to fetch total amount of countainers

---

CHANGELOG.md
go.mod
go.sum

Signed-off-by: Evgenii Stratonikov <evgeniy@morphbits.ru>

go.mod: Update neo-go to v0.99.1

---

Makefile

Signed-off-by: anikeev-yadro <a.anikeev@yadro.com>

[#255] Filter version tags for version calculation

---

netmap/netmap_contract.go
tests/netmap_test.go

Support maintenance mode

---

.github/workflows/dco.yml

Signed-off-by: anastasia prasolova <anastasia@nspcc.ru>

[nspcc-dev/nspcc-infra#840]: Add DCO check

---

netmap/netmap_contract.go

Need this for a release.
Tested on neofs-adm from https://github.com/nspcc-dev/neofs-node/pull/1903
Signed-off-by: Evgenii Stratonikov <evgeniy@morphbits.ru>

netmap: migrate from the old storage format

---

container/container_contract.go

Related to https://github.com/nspcc-dev/neofs-contract/issues/268

Register domains for 10 years instead of 1 week

---

common/version.go
netmap/netmap_contract.go

It doesn't work in 0.16.0 and I think we're closer to 0.16.1 anyway.

Fix netmap migration code

---

.github/workflows/dco.yml

It's shared, therefore it's better.

workflows: use the same DCO as others

---

contracts/container/contract.go

This should fix the problem, but I have no idea how to test is properly. We can't easily drop or expire the domain.

container: ignore some NNS errors on deletion, fix #382

---

Makefile
README.md
common/ir.go
contracts/alphabet/contract.go
contracts/alphabet/doc.go
contracts/audit/doc.go
contracts/balance/contract.go
contracts/balance/doc.go
contracts/container/doc.go
contracts/neofs/contract.go
contracts/neofs/doc.go
contracts/neofsid/doc.go
contracts/netmap/contract.go
contracts/processing/contract.go
contracts/processing/doc.go
contracts/proxy/doc.go
contracts/reputation/doc.go
debian/control
deploy/contracts.go
deploy/deploy.go
deploy/netmap.go
deploy/util.go
rpc/nns/example_test.go
rpc/nns/names.go

Be consistent, do not use "sidechain".

*: never use "the sidechain", fix main chain spelling

---

tests/container_test.go

It is planned to release and update public contracts with this feature included. Add a test that shows we may pass additional meta-fields without any errors.

container/meta: ensure meta WIP feature is extendable

---

CHANGELOG.md

CHANGELOG: release 0.22.0
